apiVersion: v1
kind: Service
metadata:
  labels:
    app: seldon
    app.kubernetes.io/instance: 'seldon-core'
    app.kubernetes.io/version: '1.9.0'
  name: seldon-webhook-service
  namespace: {{ namespace }}
spec:
  ports:
  - port: {{ webhook_port }}
    targetPort: {{ webhook_port }}
  selector:
    app.kubernetes.io/name: {{ service }}
    control-plane: seldon-controller-manager
